import assert from "node:assert/strict";
import test from "node:test";

import { searchCatalog } from "../lib/catalog-search.mjs";

const MARKER = "<!-- Generated by scripts/build-index.py. Do not edit. -->";

function generatedIndex(heading, entries) {
  return `${MARKER}\n\n# ${heading}\n\n${entries.join("\n")}\n`;
}

function bundleIndex(title, description, tags) {
  return [
    "---",
    'okf_version: "0.2"',
    "---",
    "",
    `# ${title}`,
    "",
    description,
    "",
    "## Authors",
    "",
    "* Example",
    "",
    "## Tags",
    "",
    ...tags.map((tag) => `* ${tag}`),
    "",
    "## Specifications",
    "",
    "* [Core](specification.md) - Defines behavior.",
    "",
  ].join("\n");
}

function fixtureFetch(files) {
  return async (url) => {
    const path = new URL(url).pathname.replace("/industrial-curiosity/genizah/main/", "");
    const content = files.get(path);
    return { ok: content !== undefined, status: content === undefined ? 404 : 200, text: async () => content ?? "Not found" };
  };
}

function catalogFiles() {
  return new Map([
    ["tags/index.md", generatedIndex("Tags", ["* [maps](maps/)", "* [procedural-maps](procedural-maps/)"])],
    ["tags/maps/index.md", generatedIndex("maps", ["* [Exact Maps](../../bundles/exact-maps/) - Exact match. Authors: Example."])],
    ["tags/procedural-maps/index.md", generatedIndex("procedural-maps", ["* [Procedural Maps](../../bundles/procedural-maps/) - Partial match. Authors: Example."])],
    ["bundles/exact-maps/index.md", bundleIndex("Exact Maps", "Exact match.", ["maps"])],
    ["bundles/procedural-maps/index.md", bundleIndex("Procedural Maps", "Partial match.", ["procedural-maps"])],
  ]);
}

test("ranks full matches ahead of partial matches deterministically", async () => {
  const result = await searchCatalog(["maps"], { fetch: fixtureFetch(catalogFiles()) });

  assert.deepEqual(result.candidates.map((candidate) => candidate.bundleId), ["exact-maps", "procedural-maps"]);
  assert.equal(result.candidates[0].score, 2);
  assert.equal(result.candidates[1].score, 1);
});

test("deduplicates and normalizes terms without changing candidate order", async () => {
  const result = await searchCatalog([" MAPS ", "maps", ""], { fetch: fixtureFetch(catalogFiles()) });

  assert.deepEqual(result.terms, ["maps"]);
  assert.deepEqual(result.candidates.map((candidate) => candidate.bundleId), ["exact-maps", "procedural-maps"]);
});

test("returns valid empty candidate data when no tag matches", async () => {
  const result = await searchCatalog(["absent"], { fetch: fixtureFetch(catalogFiles()) });

  assert.deepEqual(result, { terms: ["absent"], candidates: [] });
});

test("rejects malformed generated catalog pages", async () => {
  const files = catalogFiles();
  files.set("tags/index.md", "# Tags\n\n* [maps](maps/)\n");

  await assert.rejects(
    () => searchCatalog(["maps"], { fetch: fixtureFetch(files) }),
    /Malformed catalog path tags\/index\.md/,
  );
});

test("reports catalog HTTP failures with the requested path", async () => {
  await assert.rejects(
    () => searchCatalog(["maps"], { fetch: async () => ({ ok: false, status: 503 }) }),
    /tags\/index\.md: HTTP 503/,
  );
});
