export const CATALOG_OWNER = "industrial-curiosity";
export const CATALOG_REPOSITORY = "genizah";
export const CATALOG_REF = "main";

const GENERATED_MARKER = "<!-- Generated by scripts/build-index.py. Do not edit. -->";
const BUNDLE_ID_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const TAG_VALUE_PATTERN = /^\* ([a-z0-9]+(?:-[a-z0-9]+)*)$/;
const TAG_INDEX_ENTRY_PATTERN = /^\* \[([a-z0-9]+(?:-[a-z0-9]+)*)\]\(([a-z0-9]+(?:-[a-z0-9]+)*)\/\)$/;
const TAG_PAGE_ENTRY_PATTERN = /^\* \[([^\]]+)\]\(\.\.\/\.\.\/bundles\/([a-z0-9]+(?:-[a-z0-9]+)*)\/\) - (\S(?:.*\S)?) Authors: (\S(?:.*\S)?)\.$/;
const SPECIFICATION_ENTRY_PATTERN = /^\* \[[^\]]+\]\([^()\s]+\.md\) - \S(?:.*\S)?$/;

export function compareUnicodeCodePoints(left, right) {
  let leftIndex = 0;
  let rightIndex = 0;

  while (leftIndex < left.length && rightIndex < right.length) {
    const leftCodePoint = left.codePointAt(leftIndex);
    const rightCodePoint = right.codePointAt(rightIndex);
    if (leftCodePoint !== rightCodePoint) {
      return leftCodePoint < rightCodePoint ? -1 : 1;
    }
    leftIndex += leftCodePoint > 0xffff ? 2 : 1;
    rightIndex += rightCodePoint > 0xffff ? 2 : 1;
  }

  return leftIndex === left.length ? (rightIndex === right.length ? 0 : -1) : 1;
}

export function normalizeTerms(terms) {
  if (!Array.isArray(terms)) {
    throw new Error("Search terms must be an array");
  }

  const normalizedTerms = [];
  const seen = new Set();
  for (const term of terms) {
    if (typeof term !== "string") {
      throw new Error("Search terms must be strings");
    }
    const normalized = term.trim().toLowerCase();
    if (normalized !== "" && !seen.has(normalized)) {
      seen.add(normalized);
      normalizedTerms.push(normalized);
    }
  }
  return normalizedTerms;
}

function parseGeneratedPage(content, path, heading, entryPattern) {
  const lines = content.replaceAll("\r\n", "\n").split("\n");
  if (lines.at(-1) === "") {
    lines.pop();
  }
  if (
    lines.length < 4 ||
    lines[0] !== GENERATED_MARKER ||
    lines[1] !== "" ||
    lines[2] !== `# ${heading}` ||
    lines[3] !== ""
  ) {
    throw new Error(`Malformed catalog path ${path}: unexpected generated index format`);
  }

  return lines.slice(4).map((line, index) => {
    const match = entryPattern.exec(line);
    if (match === null) {
      throw new Error(`Malformed catalog path ${path}: invalid entry on line ${index + 5}`);
    }
    return match;
  });
}

function parseTagIndex(content, path) {
  const entries = parseGeneratedPage(content, path, "Tags", TAG_INDEX_ENTRY_PATTERN);
  const tags = entries.map((entry) => {
    const [, label, target] = entry;
    if (label !== target) {
      throw new Error(`Malformed catalog path ${path}: tag link label and target differ`);
    }
    return label;
  });
  validateUniqueSorted(tags, path, "tag");
  return tags;
}

function parseTagPage(content, path, tag) {
  const entries = parseGeneratedPage(content, path, tag, TAG_PAGE_ENTRY_PATTERN);
  const bundleIds = entries.map((entry) => entry[2]);
  validateUniqueSorted(bundleIds, path, "bundle");
  return bundleIds;
}

function validateUniqueSorted(values, path, name) {
  for (let index = 0; index < values.length; index += 1) {
    if (index > 0 && compareUnicodeCodePoints(values[index - 1], values[index]) >= 0) {
      throw new Error(`Malformed catalog path ${path}: ${name} entries must be unique and sorted`);
    }
  }
}

function sectionContents(lines, sections, name) {
  const matchingSections = sections.filter((section) => section.name === name);
  if (matchingSections.length !== 1) {
    throw new Error(`Bundle index requires exactly one ${name} section`);
  }
  const section = matchingSections[0];
  const nextSection = sections.find((candidate) => candidate.line > section.line);
  return lines.slice(section.line + 1, nextSection === undefined ? undefined : nextSection.line - 2);
}

function parseBundleIndex(content, path) {
  const lines = content.replaceAll("\r\n", "\n").split("\n");
  if (lines.at(-1) === "") {
    lines.pop();
  }
  if (lines[0] !== "---" || lines[1] !== 'okf_version: "0.2"' || lines[2] !== "---") {
    throw new Error(`Malformed catalog path ${path}: invalid bundle frontmatter`);
  }

  const headings = lines
    .map((line, index) => ({ line, index }))
    .filter(({ line }) => /^# /.test(line));
  if (headings.length !== 1 || headings[0].line.trim() === "#") {
    throw new Error(`Malformed catalog path ${path}: bundle index requires one non-empty H1`);
  }
  const title = headings[0].line.slice(2).trim();
  if (title === "") {
    throw new Error(`Malformed catalog path ${path}: bundle title is empty`);
  }

  const sections = lines
    .map((line, index) => ({ name: line.slice(3).trim(), line: index + 1 }))
    .filter(({ name }, index) => lines[index].startsWith("## "));
  const requiredSections = ["Authors", "Tags", "Specifications"];
  const requiredPositions = requiredSections.map((name) => {
    const position = sections.findIndex((section) => section.name === name);
    if (position === -1 || sections.filter((section) => section.name === name).length !== 1) {
      throw new Error(`Malformed catalog path ${path}: bundle index requires exactly one ${name} section`);
    }
    return position;
  });
  if (requiredPositions.join(",") !== "0,1,2") {
    throw new Error(`Malformed catalog path ${path}: required bundle sections are out of order`);
  }

  const descriptionLines = [];
  for (const line of lines.slice(headings[0].index + 1, sections[0].line - 1)) {
    const trimmed = line.trim();
    if (trimmed === "") {
      if (descriptionLines.length > 0) {
        break;
      }
    } else {
      descriptionLines.push(trimmed);
    }
  }
  const description = descriptionLines.join(" ");
  if (description === "") {
    throw new Error(`Malformed catalog path ${path}: bundle description is empty`);
  }

  const authors = sectionContents(lines, sections, "Authors");
  if (authors.length === 0 || authors.some((line) => !/^\* \S(?:.*\S)?$/.test(line))) {
    throw new Error(`Malformed catalog path ${path}: invalid Authors section`);
  }
  const tags = sectionContents(lines, sections, "Tags");
  if (tags.length === 0 || tags.some((line) => !TAG_VALUE_PATTERN.test(line))) {
    throw new Error(`Malformed catalog path ${path}: invalid Tags section`);
  }
  const tagValues = tags.map((line) => line.slice(2));
  if (new Set(tagValues).size !== tagValues.length) {
    throw new Error(`Malformed catalog path ${path}: duplicate bundle tag`);
  }
  const specifications = sectionContents(lines, sections, "Specifications");
  if (specifications.length === 0 || specifications.some((line) => !SPECIFICATION_ENTRY_PATTERN.test(line))) {
    throw new Error(`Malformed catalog path ${path}: invalid Specifications section`);
  }

  return { title, description, tags: tagValues };
}

function rawCatalogUrl({ owner, repository, ref }, path) {
  return `https://raw.githubusercontent.com/${owner}/${repository}/${ref}/${path}`;
}

async function fetchCatalogText(fetch, catalog, path) {
  let response;
  try {
    response = await fetch(rawCatalogUrl(catalog, path));
  } catch (error) {
    throw new Error(`Failed to fetch catalog path ${path}: ${error.message}`, { cause: error });
  }
  if (!response?.ok) {
    throw new Error(`Failed to fetch catalog path ${path}: HTTP ${response?.status ?? "unknown"}`);
  }
  try {
    return await response.text();
  } catch (error) {
    throw new Error(`Failed to read catalog path ${path}: ${error.message}`, { cause: error });
  }
}

function scoreBundle(bundle, terms) {
  const fullMatches = [];
  const partialMatches = [];
  for (const term of terms) {
    if (bundle.tags.includes(term)) {
      fullMatches.push(term);
    } else if (bundle.tags.some((tag) => tag.includes(term))) {
      partialMatches.push(term);
    }
  }
  return {
    ...bundle,
    fullMatches,
    partialMatches,
    matchedTermCount: fullMatches.length + partialMatches.length,
    score: fullMatches.length * 2 + partialMatches.length,
  };
}

function compareCandidates(left, right) {
  return (
    right.score - left.score ||
    right.matchedTermCount - left.matchedTermCount ||
    right.fullMatches.length - left.fullMatches.length ||
    compareUnicodeCodePoints(left.bundleId, right.bundleId)
  );
}

export async function searchCatalog(terms, {
  fetch = globalThis.fetch,
  owner = CATALOG_OWNER,
  repository = CATALOG_REPOSITORY,
  ref = CATALOG_REF,
} = {}) {
  if (typeof fetch !== "function") {
    throw new Error("A fetch implementation is required to search the catalog");
  }
  const normalizedTerms = normalizeTerms(terms);
  const catalog = { owner, repository, ref };
  const tagIndexPath = "tags/index.md";
  const tags = parseTagIndex(await fetchCatalogText(fetch, catalog, tagIndexPath), tagIndexPath);
  const matchingTags = tags.filter((tag) => normalizedTerms.some((term) => tag === term || tag.includes(term)));
  const candidateBundleIds = new Set();
  for (const tag of matchingTags) {
    const tagPath = `tags/${tag}/index.md`;
    for (const bundleId of parseTagPage(await fetchCatalogText(fetch, catalog, tagPath), tagPath, tag)) {
      candidateBundleIds.add(bundleId);
    }
  }

  const candidates = [];
  for (const bundleId of [...candidateBundleIds].sort(compareUnicodeCodePoints)) {
    if (!BUNDLE_ID_PATTERN.test(bundleId)) {
      throw new Error(`Malformed catalog path ${tagIndexPath}: invalid bundle identifier`);
    }
    const bundlePath = `bundles/${bundleId}/index.md`;
    const bundle = parseBundleIndex(await fetchCatalogText(fetch, catalog, bundlePath), bundlePath);
    const candidate = scoreBundle({ bundleId, ...bundle }, normalizedTerms);
    if (candidate.matchedTermCount > 0) {
      candidates.push(candidate);
    }
  }

  candidates.sort(compareCandidates);
  return { terms: normalizedTerms, candidates };
}
