#!/usr/bin/env python3
"""Validate authoritative OKF bundles and generate distributed tag indexes.

This deliberately supports only the repository's constrained Markdown and YAML
format; it is not a general Markdown or YAML parser.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import os
from pathlib import Path
import re
import shutil
import sys
import tempfile
from typing import Sequence
from urllib.parse import urlparse


BUNDLE_ID_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
H1_PATTERN = re.compile(r"^# (.*)$")
H2_PATTERN = re.compile(r"^## (.*)$")
LIST_ITEM_PATTERN = re.compile(r"^\* (.*)$")
SPECIFICATION_ITEM_PATTERN = re.compile(r"^\* \[([^\]]+)\]\(([^()\s]+)\) - (\S.*\S|\S)$")
MARKDOWN_LINK_PATTERN = re.compile(r"\[[^\]]*\]\(([^()\s]+)\)")
FOOTNOTE_REFERENCE_PATTERN = re.compile(r"\[\^([^\]]+)\]")
CONCEPT_SCALAR_PATTERN = re.compile(r"^([A-Za-z][A-Za-z0-9_-]*):(?: (.*))?$")
CONCEPT_LIST_ITEM_PATTERN = re.compile(r"^  - (\S.*)$")
CONCEPT_SOURCE_FIELD_PATTERN = re.compile(r"^    ([A-Za-z][A-Za-z0-9_-]*):(?: (.*))?$")
TEMPLATE_MARKER_PATTERN = re.compile(r"REPLACE_[A-Za-z0-9_]*|\{\{[^{}]+\}\}")
REQUIRED_SECTIONS = ("Authors", "Tags", "Specifications")
RESERVED_CONCEPT_FILENAMES = frozenset(("index.md", "log.md"))
GENERATED_MARKER = "<!-- Generated by scripts/build-index.py. Do not edit. -->"


@dataclass(frozen=True)
class ValidationIssue:
    path: Path
    line: int
    message: str


@dataclass(frozen=True)
class BundleMetadata:
    bundle_id: str
    title: str
    description: str
    authors: tuple[str, ...]
    tags: tuple[str, ...]
    specification_paths: tuple[Path, ...]
    index_path: Path
    bundle_root: Path


def validate_bundle_identifier(bundle_id: str) -> list[str]:
    if BUNDLE_ID_PATTERN.fullmatch(bundle_id):
        return []
    return ["Bundle identifiers must use lowercase kebab-case."]


def parse_bundle_index(
    index_path: Path,
    bundle_root: Path,
) -> tuple[BundleMetadata | None, list[ValidationIssue]]:
    """Parse one strict bundle index without producing terminal output."""
    try:
        lines = index_path.read_text(encoding="utf-8").splitlines()
    except OSError as error:
        return None, [ValidationIssue(index_path, 1, f"Unable to read bundle index: {error}")]

    issues: list[ValidationIssue] = []
    bundle_id = bundle_root.name
    for message in validate_bundle_identifier(bundle_id):
        issues.append(ValidationIssue(index_path, 1, message))

    body_start = _validate_frontmatter(index_path, lines, issues)
    if body_start is None:
        return None, issues

    h1_positions = [
        (line_number, match.group(1).strip())
        for line_number, line in enumerate(lines[body_start:], start=body_start + 1)
        if (match := H1_PATTERN.fullmatch(line))
    ]
    if not h1_positions:
        issues.append(ValidationIssue(index_path, body_start + 1, "Exactly one H1 is required after frontmatter."))
    elif len(h1_positions) > 1:
        for line_number, _ in h1_positions[1:]:
            issues.append(ValidationIssue(index_path, line_number, "Exactly one H1 is required after frontmatter."))
    title = h1_positions[0][1] if len(h1_positions) == 1 else ""
    h1_line = h1_positions[0][0] if len(h1_positions) == 1 else body_start + 1
    if len(h1_positions) == 1 and not title:
        issues.append(ValidationIssue(index_path, h1_line, "Bundle title must be non-empty."))

    sections = _find_sections(lines, body_start)
    required = _validate_required_sections(index_path, sections, issues)

    description = ""
    if len(h1_positions) == 1 and "Authors" in required:
        authors_heading_line = required["Authors"][0]
        description = _paragraph_between(lines, h1_line, authors_heading_line)
        if not description:
            issues.append(ValidationIssue(index_path, authors_heading_line, "Bundle description must be non-empty."))

    authors: tuple[str, ...] = ()
    tags: tuple[str, ...] = ()
    indexed_links: list[tuple[int, Path]] = []
    if "Authors" in required:
        authors = _parse_authors(index_path, lines, required["Authors"], sections, issues)
    if "Tags" in required:
        tags = _parse_tags(index_path, lines, required["Tags"], sections, issues)
    if "Specifications" in required:
        indexed_links.extend(_parse_specifications(
            index_path, lines, required["Specifications"], sections, issues,
        ))

    indexed_links.extend(_parse_optional_local_links(index_path, lines, sections, required, issues))
    _validate_indexed_local_links(index_path, bundle_root, indexed_links, issues)
    specification_paths = tuple(path for _, path in indexed_links)

    if issues:
        return None, issues
    return BundleMetadata(
        bundle_id=bundle_id,
        title=title,
        description=description,
        authors=authors,
        tags=tags,
        specification_paths=specification_paths,
        index_path=index_path,
        bundle_root=bundle_root,
    ), []


def _validate_frontmatter(
    index_path: Path,
    lines: list[str],
    issues: list[ValidationIssue],
) -> int | None:
    if not lines or lines[0] != "---":
        issues.append(ValidationIssue(index_path, 1, "Bundle index must start with frontmatter."))
        return None

    try:
        closing_line = lines.index("---", 1)
    except ValueError:
        issues.append(ValidationIssue(index_path, len(lines) or 1, "Bundle frontmatter must end with '---'."))
        return None

    frontmatter_lines = lines[1:closing_line]
    expected_line = 'okf_version: "0.2"'
    if frontmatter_lines != [expected_line]:
        found_expected_line = False
        for line_number, line in enumerate(frontmatter_lines, start=2):
            if line != expected_line or found_expected_line:
                issues.append(
                    ValidationIssue(
                        index_path,
                        line_number,
                        'Bundle frontmatter must contain only okf_version: "0.2".',
                    )
                )
            else:
                found_expected_line = True
        if not frontmatter_lines:
            issues.append(
                ValidationIssue(
                    index_path,
                    closing_line + 1,
                    'Bundle frontmatter must contain only okf_version: "0.2".',
                )
            )
    return closing_line + 1


def _find_sections(lines: list[str], body_start: int) -> list[tuple[str, int]]:
    return [
        (match.group(1).strip(), line_number)
        for line_number, line in enumerate(lines[body_start:], start=body_start + 1)
        if (match := H2_PATTERN.fullmatch(line))
    ]


def _validate_required_sections(
    index_path: Path,
    sections: list[tuple[str, int]],
    issues: list[ValidationIssue],
) -> dict[str, tuple[int, int]]:
    required: dict[str, tuple[int, int]] = {}
    positions: list[int] = []
    for section_name in REQUIRED_SECTIONS:
        matching_positions = [position for position, (name, _) in enumerate(sections) if name == section_name]
        if len(matching_positions) != 1:
            line = sections[matching_positions[0]][1] if matching_positions else 1
            issues.append(
                ValidationIssue(
                    index_path,
                    line,
                    f"Required section '{section_name}' must occur exactly once.",
                )
            )
            continue
        position = matching_positions[0]
        required[section_name] = (sections[position][1], position)
        positions.append(position)

    if len(positions) == len(REQUIRED_SECTIONS) and positions != sorted(positions):
        issues.append(
            ValidationIssue(index_path, sections[positions[0]][1], "Required sections must occur in Authors, Tags, Specifications order."),
        )
    return required


def _paragraph_between(lines: list[str], h1_line: int, authors_heading_line: int) -> str:
    paragraph_lines: list[str] = []
    for line in lines[h1_line:authors_heading_line - 1]:
        stripped = line.strip()
        if not stripped:
            if paragraph_lines:
                break
            continue
        paragraph_lines.append(stripped)
    return " ".join(paragraph_lines)


def _section_contents(
    lines: list[str], section: tuple[int, int], all_sections: list[tuple[str, int]],
) -> list[tuple[int, str]]:
    heading_line, section_position = section
    end_line = all_sections[section_position + 1][1] if section_position + 1 < len(all_sections) else len(lines) + 1
    return list(enumerate(lines[heading_line:end_line - 1], start=heading_line + 1))


def _section_entries(
    index_path: Path,
    lines: list[str],
    section: tuple[int, int],
    all_sections: list[tuple[str, int]],
    issues: list[ValidationIssue],
    section_name: str,
) -> list[tuple[int, str]]:
    entries: list[tuple[int, str]] = []
    for line_number, line in _section_contents(lines, section, all_sections):
        if not line.strip():
            continue
        match = LIST_ITEM_PATTERN.fullmatch(line)
        if not match or not match.group(1).strip():
            issues.append(ValidationIssue(index_path, line_number, f"{section_name} entries must be non-empty list items."))
            continue
        entries.append((line_number, match.group(1).strip()))
    return entries


def _parse_authors(
    index_path: Path,
    lines: list[str],
    section: tuple[int, int],
    sections: list[tuple[str, int]],
    issues: list[ValidationIssue],
) -> tuple[str, ...]:
    entries = _section_entries(index_path, lines, section, sections, issues, "Authors")
    if not entries:
        issues.append(ValidationIssue(index_path, section[0], "Authors must contain at least one entry."))
        return ()

    values = [value for _, value in entries]
    seen: set[str] = set()
    for line_number, value in entries:
        if value in seen:
            issues.append(ValidationIssue(index_path, line_number, f"Duplicate author: {value}"))
        seen.add(value)
    return tuple(values)


def _parse_tags(
    index_path: Path,
    lines: list[str],
    section: tuple[int, int],
    sections: list[tuple[str, int]],
    issues: list[ValidationIssue],
) -> tuple[str, ...]:
    entries = _section_entries(index_path, lines, section, sections, issues, "Tags")
    if not entries:
        issues.append(ValidationIssue(index_path, section[0], "Tags must contain at least one entry."))
        return ()

    values = [value for _, value in entries]
    seen: set[str] = set()
    for line_number, value in entries:
        if not BUNDLE_ID_PATTERN.fullmatch(value):
            issues.append(ValidationIssue(index_path, line_number, f"Tag must use lowercase kebab-case: {value}"))
        if value in seen:
            issues.append(ValidationIssue(index_path, line_number, f"Duplicate tag: {value}"))
        seen.add(value)
    return tuple(values)


def _parse_specifications(
    index_path: Path,
    lines: list[str],
    section: tuple[int, int],
    sections: list[tuple[str, int]],
    issues: list[ValidationIssue],
) -> list[tuple[int, Path]]:
    entries = _section_entries(index_path, lines, section, sections, issues, "Specifications")
    paths: list[tuple[int, Path]] = []
    for line_number, value in entries:
        match = SPECIFICATION_ITEM_PATTERN.fullmatch(f"* {value}")
        if not match or not _is_local_markdown_path(match.group(2)):
            issues.append(
                ValidationIssue(
                    index_path,
                    line_number,
                    "Specification entries must link to a relative Markdown file and include a description.",
                )
            )
            continue
        paths.append((line_number, Path(match.group(2))))
    if not paths:
        issues.append(ValidationIssue(index_path, section[0], "Specifications must contain at least one local Markdown link."))
    return paths


def _parse_optional_local_links(
    index_path: Path,
    lines: list[str],
    sections: list[tuple[str, int]],
    required: dict[str, tuple[int, int]],
    issues: list[ValidationIssue],
) -> list[tuple[int, Path]]:
    optional_paths: list[tuple[int, Path]] = []
    required_positions = {section[1] for section in required.values()}
    for position, (section_name, heading_line) in enumerate(sections):
        if position in required_positions:
            continue
        end_line = sections[position + 1][1] if position + 1 < len(sections) else len(lines) + 1
        has_content = False
        for line_number, line in enumerate(lines[heading_line:end_line - 1], start=heading_line + 1):
            if not line.strip():
                continue
            has_content = True
            match = SPECIFICATION_ITEM_PATTERN.fullmatch(line)
            if not match or not _is_local_markdown_path(match.group(2)):
                issues.append(
                    ValidationIssue(
                        index_path,
                        line_number,
                        "Optional section entries must link to a relative Markdown file and include a description.",
                    )
                )
                continue
            optional_paths.append((line_number, Path(match.group(2))))
        if not has_content:
            issues.append(
                ValidationIssue(
                    index_path,
                    heading_line,
                    f"Optional section '{section_name}' must contain at least one linked entry.",
                )
            )
    return optional_paths


def _validate_indexed_local_links(
    index_path: Path,
    bundle_root: Path,
    indexed_links: Sequence[tuple[int, Path]],
    issues: list[ValidationIssue],
) -> None:
    resolved_root = bundle_root.resolve()
    for line_number, relative_path in indexed_links:
        candidate_path = bundle_root / relative_path
        if candidate_path.is_symlink():
            issues.append(ValidationIssue(index_path, line_number, "Indexed local link must not be a symbolic link."))
            continue
        candidate = candidate_path.resolve()
        if not _is_within(candidate, resolved_root):
            issues.append(ValidationIssue(index_path, line_number, "Indexed local link escapes bundle root."))
        elif not candidate.exists():
            issues.append(ValidationIssue(index_path, line_number, "Indexed local link does not exist."))
        elif not candidate.is_file():
            issues.append(ValidationIssue(index_path, line_number, "Indexed local link must resolve to a file."))


def _is_local_markdown_path(target: str) -> bool:
    return (
        target.endswith(".md")
        and not target.startswith("/")
        and not target.startswith("#")
        and "://" not in target
        and not target.startswith("mailto:")
    )


def validate_bundle_concepts(metadata: BundleMetadata) -> list[ValidationIssue]:
    """Validate every non-reserved Markdown concept below one bundle."""
    issues: list[ValidationIssue] = []
    bundle_root = metadata.bundle_root.resolve()
    for document_path in sorted(metadata.bundle_root.rglob("*.md")):
        if document_path.name in RESERVED_CONCEPT_FILENAMES:
            continue
        if document_path.is_symlink() or not _is_within(document_path.resolve(), bundle_root):
            issues.append(ValidationIssue(document_path, 1, "Concept path escapes bundle root."))
            continue
        try:
            lines = document_path.read_text(encoding="utf-8").splitlines()
        except OSError as error:
            issues.append(ValidationIssue(document_path, 1, f"Unable to read concept: {error}"))
            continue

        frontmatter, body_start, frontmatter_issues = _read_concept_frontmatter(document_path, lines)
        issues.extend(frontmatter_issues)
        for field in ("type", "title", "description"):
            if not frontmatter.scalars.get(field):
                issues.append(ValidationIssue(document_path, 1, f"Concept frontmatter requires non-empty '{field}'."))
        if not frontmatter.tags:
            issues.append(ValidationIssue(document_path, 1, "Concept frontmatter requires at least one 'tags' entry."))
        if not frontmatter.sources:
            issues.append(ValidationIssue(document_path, 1, "Concept frontmatter requires at least one 'sources' entry."))
        for source_line, source in frontmatter.sources:
            if not source.get("id"):
                issues.append(ValidationIssue(document_path, source_line, "Concept source requires a non-empty id."))
            if not source.get("resource"):
                issues.append(ValidationIssue(document_path, source_line, "Concept source requires a non-empty resource."))
        if frontmatter.sources and not any(_is_external_https_url(source.get("resource", "")) for _, source in frontmatter.sources):
            issues.append(ValidationIssue(document_path, 1, "Concept requires at least one external https:// source resource."))

        if body_start is None:
            continue
        source_ids = {source.get("id", "") for _, source in frontmatter.sources}
        for line_number, line in enumerate(lines, start=1):
            if TEMPLATE_MARKER_PATTERN.search(line):
                issues.append(ValidationIssue(document_path, line_number, "Concept contains an unresolved template marker."))
            for match in FOOTNOTE_REFERENCE_PATTERN.finditer(line):
                source_id = match.group(1)
                if source_id not in source_ids:
                    issues.append(
                        ValidationIssue(
                            document_path,
                            line_number,
                            f"Concept footnote references undeclared source: {source_id}",
                        ),
                    )
            for match in MARKDOWN_LINK_PATTERN.finditer(line):
                target, error = resolve_bundle_link(bundle_root, document_path, match.group(1))
                if error:
                    issues.append(ValidationIssue(document_path, line_number, error))
                elif target is not None and not target.exists():
                    issues.append(ValidationIssue(document_path, line_number, "Local link does not exist."))
    return issues


@dataclass(frozen=True)
class _ConceptFrontmatter:
    scalars: dict[str, str]
    tags: tuple[str, ...]
    sources: tuple[tuple[int, dict[str, str]], ...]


def _read_concept_frontmatter(
    document_path: Path,
    lines: list[str],
) -> tuple[_ConceptFrontmatter, int | None, list[ValidationIssue]]:
    """Read only the constrained OKF frontmatter subset used by concepts."""
    issues: list[ValidationIssue] = []
    if not lines or lines[0] != "---":
        issues.append(ValidationIssue(document_path, 1, "Concept must start with frontmatter."))
        return _ConceptFrontmatter({}, (), ()), None, issues
    try:
        closing_line = lines.index("---", 1)
    except ValueError:
        issues.append(ValidationIssue(document_path, len(lines) or 1, "Concept frontmatter must end with '---'."))
        return _ConceptFrontmatter({}, (), ()), None, issues

    scalars: dict[str, str] = {}
    tags: list[str] = []
    sources: list[tuple[int, dict[str, str]]] = []
    frontmatter_lines = lines[1:closing_line]
    position = 0
    while position < len(frontmatter_lines):
        line = frontmatter_lines[position]
        match = CONCEPT_SCALAR_PATTERN.fullmatch(line)
        if not match:
            position += 1
            continue
        key, value = match.groups()
        line_number = position + 2
        if key == "tags" and value is None:
            position += 1
            while position < len(frontmatter_lines):
                item = CONCEPT_LIST_ITEM_PATTERN.fullmatch(frontmatter_lines[position])
                if not item:
                    break
                tags.append(item.group(1))
                position += 1
            continue
        if key == "sources" and value is None:
            position += 1
            while position < len(frontmatter_lines):
                item = CONCEPT_LIST_ITEM_PATTERN.fullmatch(frontmatter_lines[position])
                if not item:
                    break
                source_match = CONCEPT_SCALAR_PATTERN.fullmatch(item.group(1))
                source = {source_match.group(1): source_match.group(2) or ""} if source_match else {}
                source_line = position + 2
                position += 1
                while position < len(frontmatter_lines):
                    field = CONCEPT_SOURCE_FIELD_PATTERN.fullmatch(frontmatter_lines[position])
                    if not field:
                        break
                    source[field.group(1)] = field.group(2) or ""
                    position += 1
                sources.append((source_line, source))
            continue
        scalars[key] = value or ""
        position += 1
    return _ConceptFrontmatter(scalars, tuple(tags), tuple(sources)), closing_line + 1, issues


def resolve_bundle_link(
    bundle_root: Path,
    document_path: Path,
    raw_target: str,
) -> tuple[Path | None, str | None]:
    """Resolve local links and reject paths outside bundle_root."""
    if (
        raw_target.startswith(("http://", "https://", "mailto:", "#"))
        or not raw_target
    ):
        return None, None
    target = raw_target.split("#", 1)[0].split("?", 1)[0]
    if not target:
        return None, None
    resolved_root = bundle_root.resolve()
    base = resolved_root if target.startswith("/") else document_path.parent.resolve()
    candidate = (base / target.lstrip("/")).resolve()
    if not _is_within(candidate, resolved_root):
        return None, "Local link escapes bundle root."
    return candidate, None


def _is_within(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
    except ValueError:
        return False
    return True


def _is_external_https_url(resource: str) -> bool:
    parsed = urlparse(resource)
    return parsed.scheme == "https" and bool(parsed.netloc)


def render_tag_tree(bundles: Sequence[BundleMetadata]) -> dict[Path, str]:
    """Render the deterministic generated files relative to tags/."""
    by_tag: dict[str, list[BundleMetadata]] = {}
    for bundle in bundles:
        for tag in bundle.tags:
            by_tag.setdefault(tag, []).append(bundle)

    desired: dict[Path, str] = {}
    tag_links = "".join(f"* [{tag}]({tag}/)\n" for tag in sorted(by_tag))
    desired[Path("index.md")] = f"{GENERATED_MARKER}\n\n# Tags\n\n{tag_links}"
    for tag in sorted(by_tag):
        entries = "".join(_render_tag_entry(bundle) for bundle in sorted(by_tag[tag], key=lambda item: item.bundle_id))
        desired[Path(tag) / "index.md"] = f"{GENERATED_MARKER}\n\n# {tag}\n\n{entries}"
    return desired


def _render_tag_entry(bundle: BundleMetadata) -> str:
    authors = ", ".join(bundle.authors)
    return (
        f"* [{bundle.title}](../../bundles/{bundle.bundle_id}/) - {bundle.description} "
        f"Authors: {authors}.\n"
    )


def compare_tag_tree(root: Path, desired: dict[Path, str]) -> list[Path]:
    """Return changed, missing, and stale generated paths relative to tags/."""
    tags_root = root.resolve() / "tags"
    if tags_root.is_symlink() or (tags_root.exists() and not tags_root.is_dir()):
        return list(desired)
    differences: list[Path] = []
    for relative_path, expected in desired.items():
        actual_path = tags_root / relative_path
        if actual_path.is_symlink() or actual_path.parent.is_symlink():
            differences.append(relative_path)
            continue
        try:
            actual = actual_path.read_text(encoding="utf-8")
        except FileNotFoundError:
            differences.append(relative_path)
            continue
        except OSError:
            differences.append(relative_path)
            continue
        if actual != expected:
            differences.append(relative_path)

    if tags_root.is_dir() and not tags_root.is_symlink():
        desired_directories = {path.parts[0] for path in desired if len(path.parts) > 1}
        for entry in sorted(tags_root.iterdir()):
            if entry.name == "index.md":
                continue
            if entry.is_symlink() or not entry.is_dir():
                differences.append(Path(entry.name))
                continue
            if entry.name not in desired_directories:
                differences.append(Path(entry.name) / "index.md")
                continue
            for child in sorted(entry.iterdir()):
                if child.name != "index.md":
                    differences.append(Path(entry.name) / child.name)
    return differences


def write_tag_tree(root: Path, desired: dict[Path, str]) -> None:
    """Safely synchronize generated tag files after a complete preflight."""
    repository_root = root.resolve()
    tags_root = repository_root / "tags"
    collisions = _tag_tree_collisions(tags_root, desired)
    if collisions:
        raise ValueError("\n".join(collisions))

    repository_root.mkdir(parents=True, exist_ok=True)
    staging_root = Path(tempfile.mkdtemp(prefix=".tags-staging-", dir=repository_root))
    staging_tags = staging_root / "tags"
    backup_root: Path | None = None
    try:
        staging_tags.mkdir()
        _write_tag_files(staging_tags, desired)
        if tags_root.exists():
            backup_root = Path(tempfile.mkdtemp(prefix=".tags-backup-", dir=repository_root))
            backup_root.rmdir()
            os.replace(tags_root, backup_root)
        os.replace(staging_tags, tags_root)
    except BaseException:
        if backup_root is not None and backup_root.exists() and not tags_root.exists():
            os.replace(backup_root, tags_root)
        raise
    finally:
        shutil.rmtree(staging_root, ignore_errors=True)
        if backup_root is not None and backup_root.exists():
            shutil.rmtree(backup_root)


def _write_tag_files(tags_root: Path, desired: dict[Path, str]) -> None:
    for relative_path, contents in desired.items():
        destination = tags_root / relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        _replace_text_atomically(destination, contents)


def _tag_tree_collisions(tags_root: Path, desired: dict[Path, str]) -> list[str]:
    collisions: list[str] = []
    if tags_root.is_symlink() or (tags_root.exists() and not tags_root.is_dir()):
        return [f"{tags_root}: tags output location is not a directory."]
    if not tags_root.exists():
        return collisions

    desired_directories = {path.parts[0] for path in desired if len(path.parts) > 1}
    for entry in sorted(tags_root.iterdir()):
        if entry.name == "index.md":
            continue
        if entry.is_symlink() or not entry.is_dir():
            collisions.append(f"{entry}: unexpected entry in generated tag tree.")
            continue
        if entry.name not in desired_directories:
            continue
        for child in sorted(entry.iterdir()):
            if child.name != "index.md":
                collisions.append(f"{child}: unexpected entry in generated tag directory.")

    for relative_path in desired:
        destination = tags_root / relative_path
        if destination.parent != tags_root and destination.parent.exists() and not destination.parent.is_dir():
            collisions.append(f"{destination.parent}: generated tag location is not a directory.")
            continue
        if destination.exists() or destination.is_symlink():
            if destination.is_symlink():
                collisions.append(f"{destination}: refusing to replace a symbolic link.")
                continue
            try:
                contents = destination.read_text(encoding="utf-8")
            except OSError as error:
                collisions.append(f"{destination}: unable to inspect generated file: {error}")
                continue
            if not contents.startswith(GENERATED_MARKER):
                collisions.append(f"{destination}: refusing to replace an unmarked generated file.")

    for tag_directory in sorted(path for path in tags_root.iterdir() if path.is_dir() or path.is_symlink()):
        if tag_directory.is_symlink():
            collisions.append(f"{tag_directory}: refusing to inspect a symbolic link.")
            continue
        if tag_directory.name in desired_directories:
            continue
        stale_index = tag_directory / "index.md"
        if set(tag_directory.iterdir()) != {stale_index}:
            collisions.append(f"{tag_directory}: stale generated directory must contain only index.md.")
            continue
        if stale_index.is_symlink():
            collisions.append(f"{stale_index}: refusing to inspect a symbolic link.")
            continue
        try:
            contents = stale_index.read_text(encoding="utf-8")
        except OSError as error:
            collisions.append(f"{stale_index}: unable to inspect stale generated file: {error}")
            continue
        if not contents.startswith(GENERATED_MARKER):
            collisions.append(f"{stale_index}: refusing to delete an unmarked generated file.")
    return collisions


def _replace_text_atomically(destination: Path, contents: str) -> None:
    file_descriptor, temporary_name = tempfile.mkstemp(prefix=f".{destination.name}.", dir=destination.parent)
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8", newline="") as temporary_file:
            temporary_file.write(contents)
        os.replace(temporary_path, destination)
    except BaseException:
        temporary_path.unlink(missing_ok=True)
        raise


def main(argv: Sequence[str] | None = None) -> int:
    """Validate indexes below one repository root and report terminal errors."""
    parser = argparse.ArgumentParser(description="Validate authoritative bundle indexes.")
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="repository root containing bundles/",
    )
    parser.add_argument("--check", action="store_true", help="report tag-index drift without writing files")
    parser.add_argument(
        "--bundles",
        nargs="*",
        default=None,
        metavar="ID",
        help="validate concepts only for the named existing bundles",
    )
    arguments = parser.parse_args(argv)
    repository_root = arguments.root.resolve()
    bundles_root = repository_root / "bundles"
    if bundles_root.is_symlink():
        print(f"{bundles_root}:1: bundles directory must not be a symbolic link.", file=sys.stderr)
        return 1
    if not bundles_root.is_dir() or not _is_within(bundles_root.resolve(), repository_root):
        print(f"{bundles_root}:1: bundles directory does not exist.", file=sys.stderr)
        return 1

    issues: list[ValidationIssue] = []
    metadata_by_id: dict[str, BundleMetadata] = {}
    for bundle_root in sorted(bundles_root.iterdir()):
        if bundle_root.is_symlink():
            issues.append(ValidationIssue(bundle_root, 1, "Bundle directory must not be a symbolic link."))
            continue
        if not bundle_root.is_dir():
            continue
        if not _is_within(bundle_root.resolve(), repository_root):
            issues.append(ValidationIssue(bundle_root, 1, "Bundle directory escapes repository root."))
            continue
        index_path = bundle_root / "index.md"
        if index_path.is_symlink():
            issues.append(ValidationIssue(index_path, 1, "Bundle index must not be a symbolic link."))
            continue
        if not _is_within(index_path.resolve(), repository_root):
            issues.append(ValidationIssue(index_path, 1, "Bundle index escapes repository root."))
            continue
        metadata, bundle_issues = parse_bundle_index(index_path, bundle_root)
        issues.extend(bundle_issues)
        if metadata is not None:
            metadata_by_id[metadata.bundle_id] = metadata

    if arguments.bundles is None:
        concepts_to_validate = metadata_by_id.values()
    else:
        requested_ids = set(arguments.bundles)
        concepts_to_validate = (
            metadata for bundle_id, metadata in metadata_by_id.items() if bundle_id in requested_ids
        )
    for metadata in concepts_to_validate:
        issues.extend(validate_bundle_concepts(metadata))

    for issue in issues:
        print(f"{issue.path}:{issue.line}: {issue.message}", file=sys.stderr)
    if issues:
        return 1

    desired = render_tag_tree(list(metadata_by_id.values()))
    if arguments.check:
        differences = compare_tag_tree(repository_root, desired)
        for relative_path in differences:
            print(f"{repository_root / 'tags' / relative_path}: generated tag index is missing, changed, or stale.", file=sys.stderr)
        return 1 if differences else 0

    try:
        write_tag_tree(repository_root, desired)
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
